In [118]:
### numpy- play with numbers
###pandas-dataset
###matplotib-data visualization
### sseaboard- data visualization
#scipy-satistical
#sklearn -Algorithm
import numpy as np

In [119]:
simple_list=[6,7,9]
simple_list


[6, 7, 9]

In [25]:
np.array=[(1,2,3)]
np.array

[(1, 2, 3)]

In [32]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [42]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [58]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [59]:
np.random.rand(3,5)

array([[0.1369139 , 0.50662767, 0.42939595, 0.96073013, 0.20437584],
       [0.42557239, 0.61307938, 0.53815154, 0.96832737, 0.17532618],
       [0.18223648, 0.31693186, 0.62628896, 0.71179605, 0.44253302]])

In [68]:
sample_array=np.arange(30)
np.sample_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [81]:
np.random.rand(0,10,50)

array([], shape=(0, 10, 50), dtype=float64)

In [92]:
np.random.rand(10,20,10)

array([[[0.31268175, 0.11884079, 0.92390757, ..., 0.27485592,
         0.58434733, 0.95158854],
        [0.89871636, 0.8668258 , 0.68449617, ..., 0.80925894,
         0.77338268, 0.03401239],
        [0.06339128, 0.96342022, 0.39627833, ..., 0.26820779,
         0.6238431 , 0.51574095],
        ...,
        [0.4906873 , 0.80975164, 0.81596207, ..., 0.33013083,
         0.32806248, 0.19394881],
        [0.85842395, 0.24286386, 0.88414303, ..., 0.53369246,
         0.63317173, 0.33862158],
        [0.79732292, 0.07804311, 0.57724999, ..., 0.49097584,
         0.69156042, 0.27334399]],

       [[0.04019172, 0.65644943, 0.0713966 , ..., 0.85630139,
         0.38359586, 0.28001098],
        [0.61583846, 0.78979249, 0.00478618, ..., 0.20965601,
         0.586161  , 0.56445925],
        [0.29156428, 0.03346742, 0.29148532, ..., 0.61694644,
         0.84421089, 0.56764797],
        ...,
        [0.65775956, 0.99240261, 0.25428861, ..., 0.60389403,
         0.08323339, 0.38304196],
        [0.5

In [97]:
rand_array=np.random.randint(0,10,50)
np.rand_array.max()


TypeError: ignored

In [101]:
a=np.eye(5)
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [104]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [107]:
sample_array[4]

14

In [108]:
sample_array[2:5]

array([12, 13, 14])

In [111]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [115]:
sample_array=np.arange(1,20,2)
sample_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [116]:
sample_array=np.arange(10,100,5)
sample_array

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [117]:
sample_array=np.arange(40)
sample_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])