# Numpy: Package for multidimensional array

### list

In [1]:
import numpy as np  

In [25]:
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [49]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [5]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
np.arange(500)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [50]:
np.zeros (10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [58]:
np.ones(20,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [61]:
np.zeros(20,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [66]:
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [67]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [69]:
np.random.rand(3,5)

array([[0.97808918, 0.11459416, 0.12571322, 0.0240669 , 0.99957784],
       [0.30451313, 0.78873433, 0.18771438, 0.40892494, 0.17217303],
       [0.64486087, 0.69690474, 0.88035068, 0.06806964, 0.4513453 ]])

In [72]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [73]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
np.zeros((5,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
np.linspace(3,500,70)

array([  3.        ,  10.20289855,  17.4057971 ,  24.60869565,
        31.8115942 ,  39.01449275,  46.2173913 ,  53.42028986,
        60.62318841,  67.82608696,  75.02898551,  82.23188406,
        89.43478261,  96.63768116, 103.84057971, 111.04347826,
       118.24637681, 125.44927536, 132.65217391, 139.85507246,
       147.05797101, 154.26086957, 161.46376812, 168.66666667,
       175.86956522, 183.07246377, 190.27536232, 197.47826087,
       204.68115942, 211.88405797, 219.08695652, 226.28985507,
       233.49275362, 240.69565217, 247.89855072, 255.10144928,
       262.30434783, 269.50724638, 276.71014493, 283.91304348,
       291.11594203, 298.31884058, 305.52173913, 312.72463768,
       319.92753623, 327.13043478, 334.33333333, 341.53623188,
       348.73913043, 355.94202899, 363.14492754, 370.34782609,
       377.55072464, 384.75362319, 391.95652174, 399.15942029,
       406.36231884, 413.56521739, 420.76811594, 427.97101449,
       435.17391304, 442.37681159, 449.57971014, 456.78

In [77]:
np.random.randint(2,100)

45

In [78]:
np.random.randint(2,100)

31

In [79]:
np.random.randint(2,100)

49

In [83]:
np.random.randint(4,400) ##random output

230

In [84]:
np.random.randint(4,400)

341

In [86]:
rand_array=np.random.randint(0,10,50)
rand_array

array([8, 8, 4, 6, 7, 9, 1, 5, 3, 1, 0, 1, 6, 4, 3, 2, 3, 7, 9, 9, 1, 9,
       6, 4, 8, 5, 2, 4, 5, 7, 7, 7, 6, 1, 0, 6, 7, 1, 9, 6, 4, 4, 8, 4,
       5, 6, 3, 2, 6, 0])

<class 'NameError'>: name 'randint' is not defined

In [101]:
a=np.eye(5) 
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
a=np.random.rand(2,3)
a

array([[0.31379701, 0.10917675, 0.99211968],
       [0.01413096, 0.94899342, 0.82470405]])

In [106]:
a.T

array([[0.31379701, 0.01413096],
       [0.10917675, 0.94899342],
       [0.99211968, 0.82470405]])

In [110]:
sample_array=np.arange(50)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [107]:
np.random.randint(20,56,100)

array([48, 27, 30, 39, 39, 38, 30, 21, 50, 47, 49, 31, 55, 22, 55, 24, 50,
       21, 34, 27, 48, 22, 38, 47, 34, 27, 37, 44, 44, 29, 46, 31, 50, 26,
       47, 50, 51, 52, 41, 47, 27, 36, 42, 49, 23, 40, 49, 31, 45, 49, 32,
       20, 22, 29, 29, 21, 49, 38, 30, 50, 49, 26, 31, 33, 50, 26, 41, 47,
       52, 48, 46, 44, 38, 41, 23, 54, 39, 29, 28, 45, 26, 32, 29, 46, 34,
       40, 24, 47, 33, 33, 43, 49, 47, 41, 51, 24, 53, 21, 39, 41])

In [113]:
rand_array.argmax()

5

In [115]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [116]:
sample_array[1:4]

array([11, 12, 13])

In [119]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [121]:
sample_array[8]

18

### Tuples

In [70]:
sample_tuple=(1,2,3,4,5,6,7)
sample_tuple

(1, 2, 3, 4, 5, 6, 7)

In [71]:
sample_tuple[0]

1

In [15]:
sample_tuple[-5]

3

In [18]:
sample_tuple[-1]

7

In [19]:
sample_tuple[0]=100

<class 'TypeError'>: 'tuple' object does not support item assignment

### dictionary

In [27]:
dict_1={'name':"arun","hobbies":["painting","singing"],5:2.3}

In [28]:
type(dict_1)

dict

In [29]:
dict_1

{'name': 'arun', 'hobbies': ['painting', 'singing'], 5: 2.3}

In [31]:
dict_1.keys()

dict_keys(['name', 'hobbies', 5])

In [34]:
dict_1.values()

dict_values(['arun', ['painting', 'singing'], 2.3])

In [35]:
dict_1['hobbies']

['painting', 'singing']

In [41]:
dict_1["name"]="latha"

In [42]:
dict_1

{'name': 'latha', 'hobbies': ['painting', 'singing'], 5: 2.3}

#### key-value pair
#### we can retrive values using index
#### mutable 
#### {}

In [45]:
import numpy as np