### selection technique

In [2]:
import numpy as np 

In [3]:
sample_array=np.arange(1,20)

In [4]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [6]:
np.exp(sample_array) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [7]:
np.sqrt(sample_array) 

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [8]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [9]:
np.max(sample_array)

19

In [10]:
np.min(sample_array)

1

In [11]:
np.argmax(sample_array)

18

In [13]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [15]:
np.var(sample_array)

30.0

In [16]:
np.mean(sample_array)

10.0

In [17]:
np.std(sample_array)

5.477225575051661

In [19]:
array=np.random.randn(3,4)
array

array([[ 1.32666572, -0.04564872, -0.73088124, -1.43281873],
       [ 0.52732159, -1.09968331,  0.08410471, -0.43789942],
       [ 1.48696502,  0.34623473, -0.64690163,  1.40613475]])

In [21]:
np.round(array,decimals=2)

array([[ 1.33, -0.05, -0.73, -1.43],
       [ 0.53, -1.1 ,  0.08, -0.44],
       [ 1.49,  0.35, -0.65,  1.41]])

In [23]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [25]:
sports

array(['golf', 'cricket', 'fball', 'cricket'], dtype='<U7')